# Generated by Django 2.1.5 on 2019-09-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
